### ISSUE TITLE
Enable posting of PDF files in articles

### ISSUE THREAD

**Issue by gonzalezmorales** [UNStats/covid-19-response#142]
@454de6e - Need add links to pdf files for Palestine

_Originally posted by @gonzalezmorales in https://github.com/UNStats/covid-19-response/pull/141#issuecomment-611471815_

**Comment by 454de6e** [comment]
More on why this needs some work: https://github.com/UNStats/covid-19-response/issues/149#issuecomment-611780566.

**Comment by 454de6e** [comment]
@gonzalezmorales You can place PDF in `static` folder and link it in Markdown file.

Example: A file `static/some-document.pdf` will be copied by Gatsby as static file and can be linked like this: `[some document](/some-document.pdf)`.

See #385 for examples.

cc: @tbatun @narain13
