### ISSUE TITLE
PDFs with translations open as downloads and not with in-browser preview

### ISSUE THREAD

**Issue by 454de6e** [UNStats/covid-19-response#385]
<img width="839" alt="Screen Shot 2020-08-05 at 10 30 12 PM" src="https://user-images.githubusercontent.com/1482402/89483931-45c17400-d76b-11ea-9949-630d0dded3a1.png">

**Comment by ValchanOficial** [comment]
Did you tried ?
[PDF](URL){:target="_blank"}

**Comment by 454de6e** [comment]
@ValchanOficial This was an issue with the PDFs not linked up correctly. It's should be fixed now.

Thank you for your suggestion and please feel free to open a pull request if you notice anything else.
