### ISSUE TITLE
Every link on production website links to homepage

### ISSUE THREAD

**Issue by maiertech** [UNStats/covid-19-response#398]
In this production deployment https://vercel.com/unstats/covid-19-response/aw6m0u6ln every link links to the homepage. 

<img width="1168" alt="Screen Shot 2020-08-17 at 2 03 34 PM" src="https://user-images.githubusercontent.com/1482402/90428926-bda86c00-e092-11ea-848f-27b131ee2b60.png">

It looks like some of the GraphQL queries generating event pages resulted in an error:

<img width="1226" alt="Screen Shot 2020-08-17 at 2 07 44 PM" src="https://user-images.githubusercontent.com/1482402/90429207-3dced180-e093-11ea-9d6c-a7632792a42a.png">

**Comment by 454de6e** [comment]
The root cause of this issue is not clear, but the workaround is to trigger a redeploy for the defective build in the Vercel dashboard.

**Comment by 454de6e** [comment]
@gonzalezmorales @danielb75 Have you had this issue recently?

**Comment by maiertech** [comment]
Should be fixed with https://github.com/UNStats/covid-19-response/issues/489.
